# Generated by Django 5.0.7 on 2024-07-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultetyName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name=520)),
                ('website', models.URLField(max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeCode', models.CharField(blank=True, max_length=255, null=True)),
                ('routeName', models.CharField(max_length=255)),
                ('routeType', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistratura', 'Magistratura')], default='bakalavr', max_length=120)),
                ('daySum', models.IntegerField(blank=True, null=True)),
                ('nightSum', models.IntegerField(blank=True, null=True)),
                ('sirtqiSum', models.IntegerField(blank=True, null=True)),
                ('dayKvota', models.IntegerField(blank=True, null=True)),
                ('nightKvota', models.IntegerField(blank=True, null=True)),
                ('sirtqiKvota', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('russian', 'Russian'), ('english', 'English'), ('uzb', 'Uzb')], default='uzb', max_length=120)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univery.faculty')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univery.institute')),
            ],
        ),
    ]
