# Generated by Django 5.0.7 on 2024-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='contract',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='grand',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
