# Generated by Django 5.0.7 on 2024-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univery', '0002_institute_contract_institute_grand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.RemoveField(
            model_name='institute',
            name='logo',
        ),
    ]
