# Generated by Django 5.0.7 on 2024-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univery', '0003_modellogo_remove_institute_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.TextField(max_length=520),
        ),
    ]
