# Generated by Django 5.0.7 on 2024-07-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoEntry',
        ),
    ]
